export enum Status {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  PENDING = 'pending',
  SUSPENDED = 'suspended',
  DELETED = 'deleted',
  ARCHIVED = 'archived',
  COMPLETED = 'completed',
  FAILED = 'failed',
  PROCESSING = 'processing',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  ON_HOLD = 'on_hold',
  CANCELLED = 'cancelled',
  DRAFT = 'draft',
  VERIFIED = 'verified',
  UNVERIFIED = 'unverified',
  EXPIRED = 'expired',
  NOT_STARTED = 'not_started',
  IN_PROGRESS = 'in_progress',
  READY = 'ready',
  UNAVAILABLE = 'unavailable',
  AVAILABLE = 'available',
  CONFIRMED = 'confirmed',
  UNCONFIRMED = 'unconfirmed',
  SUBMITTED = 'submitted',
  UNSUBMITTED = 'unsubmitted',
  REVOKED = 'revoked',
  REINSTATED = 'reinstated',
  BLOCKED = 'blocked',
  UNBLOCKED = 'unblocked',
  LOCKED = 'locked',
  UNLOCKED = 'unlocked',
  EXPIRED_SOON = 'expired_soon',
  NOT_ELIGIBLE = 'not_eligible',
  ELIGIBLE = 'eligible',
  IN_REVIEW = 'in_review',
}
// This enum can be used to represent various statuses in an application.
// It can be extended or modified based on specific requirements.
